[2024-09-13T14:42:31.113+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-13T14:42:31.158+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_etl_dag.run_etl scheduled__2024-09-12T00:00:00+00:00 [queued]>
[2024-09-13T14:42:31.167+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_etl_dag.run_etl scheduled__2024-09-12T00:00:00+00:00 [queued]>
[2024-09-13T14:42:31.167+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-13T14:42:31.208+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_etl> on 2024-09-12 00:00:00+00:00
[2024-09-13T14:42:31.215+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=88) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-13T14:42:31.218+0000] {standard_task_runner.py:63} INFO - Started process 90 to run task
[2024-09-13T14:42:31.219+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'youtube_etl_dag', 'run_etl', 'scheduled__2024-09-12T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/youtube_etl_dag.py', '--cfg-path', '/tmp/tmpvgm55xed']
[2024-09-13T14:42:31.222+0000] {standard_task_runner.py:91} INFO - Job 24: Subtask run_etl
[2024-09-13T14:42:31.391+0000] {task_command.py:426} INFO - Running <TaskInstance: youtube_etl_dag.run_etl scheduled__2024-09-12T00:00:00+00:00 [running]> on host 5c5aafcec616
[2024-09-13T14:42:31.585+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_etl_dag' AIRFLOW_CTX_TASK_ID='run_etl' AIRFLOW_CTX_EXECUTION_DATE='2024-09-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-12T00:00:00+00:00'
[2024-09-13T14:42:31.586+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-13T14:42:31.807+0000] {warnings.py:112} WARNING - /opt/***/dags/youtube_etl_dag.py:50: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfredshift['duración_minutos'] = dfredshift['duración'].apply(convert_to_minutes)

[2024-09-13T14:42:39.812+0000] {logging_mixin.py:188} INFO - Unable to connect to Redshift.
[2024-09-13T14:42:39.813+0000] {logging_mixin.py:188} INFO - could not translate host name "data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com" to address: Temporary failure in name resolution
[2024-09-13T14:42:39.813+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-09-13T14:42:39.814+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-13T14:42:39.821+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=youtube_etl_dag, task_id=run_etl, run_id=scheduled__2024-09-12T00:00:00+00:00, execution_date=20240912T000000, start_date=20240913T144231, end_date=20240913T144239
[2024-09-13T14:42:39.996+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-09-13T14:42:40.004+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
